### ISSUE TITLE
Add compatibility for Linux OS

### ISSUE THREAD

**Issue by sakshi2912** [TradeMythBuster/Stock-Options-Graph#5]
The current implementation can be run only on Windows.
The problem arises when the optionicon.ico file has to be read by Tkinter.
Linux, however can not use .ico , instead it would require .xbm or .xmp.

Add conditional statements to determine if the OS is windows or Linux and add appropriate statements under each.
You are welcome to add the same functionality for Mac OS as well.

You can find the picture to be used, named as : **optionicon.png**

**To reproduce the issue**:
Run the .py file on a Linux OS.

**Expected output**:
Code should run without error

**Current output**:
tkinter.TclError...

**Comment by sawyer1997** [comment]
@sakshi2912 Can I try?

**Comment by sakshi2912** [comment]
> @sakshi2912 Can I try?

Yes, go ahead

**Comment by RakshithRAcharya** [comment]
I Have done this...I am gonna make a PR...Please accept...Its working

**Comment by RakshithRAcharya** [comment]
@sakshi2912 this was 100 bounty when I did it......and I was given 100 bounty also......but now why was my bounty also changed to 50

**Comment by sakshi2912** [comment]
> @sakshi2912 this was 100 bounty when I did it......and I was given 100 bounty also......but now why was my bounty also changed to 50

So the old labels were put up each individual repo maintainer.
But now there is one team which is looking at all the bounties cross- repos. so that's where they're standardising / uniforming the whole thing.
