### ISSUE TITLE
Add configurable colors

### ISSUE THREAD

**Issue by srujandeshpande** [TradeMythBuster/Stock-Options-Graph#7]
The background and heading colors are set by defualt. Create a configuration file  that stores the current colors. 
Changing colors in the file should change the colors in the program

**Comment by The-Shwin** [comment]
Hi, could I try out this issue please? I believe I have a simple implementation that will be easy to edit to customize the colors and added more configurable enhancements to further down the line.

**Comment by The-Shwin** [comment]
Thanks, I think I have what you wanted. Submitted a PR. Please let me know if you have something else you wanted and I can look into it.

**Comment by sakshi2912** [comment]
> Thanks, I think I have what you wanted. Submitted a PR. Please let me know if you have something else you wanted and I can look into it.

Can you provide a Screenshot for this?

**Comment by The-Shwin** [comment]
> 
> 
> > Thanks, I think I have what you wanted. Submitted a PR. Please let me know if you have something else you wanted and I can look into it.
> 
> Can you provide a Screenshot for this?

Sure, I've attached a couple of different colors to demonstrate, along with the config.py file
![image](https://user-images.githubusercontent.com/11012179/97099579-05cea680-1661-11eb-9e44-3ba248ddae7a.png)
![image](https://user-images.githubusercontent.com/11012179/97099588-24cd3880-1661-11eb-80b0-634735aac634.png)
![image](https://user-images.githubusercontent.com/11012179/97099627-7c6ba400-1661-11eb-807a-bc9cfbca3690.png)

Does this help?

**Comment by sakshi2912** [comment]
Yup ! That's great! Please ignore the same comment on PR

**Comment by RakshithRAcharya** [comment]
Can I take this up??

**Comment by sakshi2912** [comment]
> Can I take this up??

Yes, go ahead.
